spring:
  application:
    name: spring-ai-rag-expert
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
       options:
         model: text-embedding-3-small
      chat:
        options:
          model: gpt-3.5-turbo
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        database-name: "default"
        collection-name: "vector_store"
        embedding-dimension: 1536
        index-type: IVF_FLAT
        metric-type: cosine
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv